<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="Local.props" Condition="Exists('Local.props')" />
	<Import Project="Build.props" />

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<OutputType>Library</OutputType>
		<RootNamespace>ShareMoreXP</RootNamespace>
		<AssemblyName>ShareMoreXP</AssemblyName>
		<AssemblyVersion>1.0.0</AssemblyVersion>
		<FileVersion>1.0.0</FileVersion>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<DefineConstants>$(GameVersion)</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
		<None Include="LICENSE.txt" CopyToOutputDirectory="Always" />
		<None Include="Mod\ModInfo.xml" TargetPath="ModInfo.xml" CopyToOutputDirectory="Always" />
		<None Include="Mod\ModConfig.xml" TargetPath="ModConfig.xml" CopyToOutputDirectory="Always" />
		<None Include="UI\ui_game_symbol_shared_xp.png" TargetPath="UIAtlases\UIAtlas\ui_game_symbol_shared_xp.png" CopyToOutputDirectory="Always" />
		<None Include="UI\ui_game_symbol_trap_xp.png" TargetPath="UIAtlases\UIAtlas\ui_game_symbol_trap_xp.png" CopyToOutputDirectory="Always" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="DashTheDev.7D2D.ModCore" Version="1.0.3" />
	</ItemGroup>
</Project>